spring:
  cloud:
    gateway:
      routes:
        - id : r1
          uri: http://localhost:8086/
          predicates:
            - Path= /customers/**
        - id: r2
          uri: http://localhost:8083/
          predicates:
            - Path= /products/**


